### ISSUE TITLE
Unable to Build dita-extension-custom-dita-map-node-renderering project

### ISSUE THREAD

**Issue by reifsnid** [oxygenxml-incubator/oxygen-sample-frameworks#1]
Hi,

I'm unable to build the dita-extension-custom-dita-map-node-renderering project.

Eclipse throws the following error:

"The POM for com.jidesoft:jide-oss:jar:3.7.14-SNAPSHOT is missing, no dependency information available"

This seems to be related to the oxygen.sdk.version defined in the pom.xml. Changing the version number to 24.1.0 lets me successfully build the project.

**Comment by raducoravu** [comment]
Thanks for the report. We fixed this problem in the latest 26.1.0.1 SDK, I updated the sample project's pom.xml to use that instead.

**Comment by reifsnid** [comment]
Hi @raducoravu,

Thank you for your quick action and updating the project's pom.xml. 

Unfortunately, I'm now encountering a different error when trying to package the project, even after pulling the latest changes:

"The following artifacts could not be resolved: com.oxygenxml:oxygen-jide:jar:1.0-SNAPSHOT (absent): Could not find artifact com.oxygenxml:oxygen-jide:jar:1.0-SNAPSHOT"

**Comment by raducoravu** [comment]
@reifsnid Oops, it seems our public Maven repo does not have this specific artifact, I will try to rectify this and reply back.

**Comment by reifsnid** [comment]
Thank you @raducoravu!

**Comment by ctalau** [comment]
While we fix our Maven repository, you can exclude the "com.oxygenxml:oxygen-jide" artifact from the pom.xml file of your project by adding an "exclusion" element to the oxygen-sdk dependency.

**Comment by reifsnid** [comment]
Thank you @ctalau! That worked and we're able to package the project.

**Comment by raducoravu** [comment]
In the meantime we also made the oxygen-jide artifact available in our public repo.
